import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "highlight.js/styles/a11y-dark.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "ruehan.blog",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="w-full h-16 backdrop-blur-sm sticky top-0 z-10 shadow-sm">
					<Link href={"/"}>Home</Link>
				</nav>
				{children}
			</body>
		</html>
	);
}
