"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "highlight.js/styles/a11y-dark.css";
import Link from "next/link";
import "leaflet/dist/leaflet.css";
import "leaflet-routing-machine/dist/leaflet-routing-machine.css";
import { usePathname } from "next/navigation";
import { Headphones } from "lucide-react";

const reko = localFont({
	src: "../font/NanumSquareR.ttf",
});

// export const metadata: Metadata = {
// 	title: "ruehan.blog",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const pathname = usePathname();
	return (
		<html lang="en">
			<body className={reko.className}>
				{pathname !== "/play" ? (
					<nav className="w-full h-16 backdrop-blur-sm sticky top-0 z-10 shadow-sm flex justify-center items-center relative">
						<Link href={"/"} className="text-2xl custom-font">
							Ruehan.blog
						</Link>
						<div className="absolute right-10 flex items-center space-x-4">
							<Link href={"https://github.com/ruehan"} className="text-2xl custom-font">
								GitHub
							</Link>
							<Link href={"/play"} className="text-2xl custom-font">
								<Headphones size={24} />
							</Link>
						</div>
					</nav>
				) : null}
				{children}
			</body>
		</html>
	);
}
